"""
Basic Usage Example

This script demonstrates the most simple way to use the Multi-Agent Blog Generator.
"""

from src.agents.orchestrator import MultiAgentOrchestrator


def main():
    # Initialize the orchestrator
    print("Initializing Multi-Agent Blog Generator...")
    orchestrator = MultiAgentOrchestrator()
    
    # Define your topic
    topic = "The Future of AI Agents in 2026"
    
    print(f"\nGenerating blog post about: {topic}")
    print("This may take 30-60 seconds...\n")
    
    # Run the multi-agent system
    result = orchestrator.run(
        topic=topic,
        user_requirements="Focus on practical applications and business impact",
        target_audience="business professionals",
        tone="professional",
        word_count=600
    )
    
    # Extract results
    blog_title = result["blog_title"]
    blog_post = result["blog_post"]
    metadata = result["blog_metadata"]
    quality_score = result.get("quality_score")
    
    # Display results
    print("="*80)
    print(f"\n{blog_title}\n")
    print("="*80)
    print(f"\n{blog_post}\n")
    print("="*80)
    
    # Display metadata
    print(f"\nMetadata:")
    print(f"  - Word Count: {metadata['word_count']}")
    print(f"  - Paragraphs: {metadata['paragraph_count']}")
    print(f"  - Estimated Reading Time: {metadata['estimated_reading_time']} minutes")
    if quality_score:
        print(f"  - Quality Score: {quality_score:.2f}")
    
    # Display execution times
    print(f"\nExecution Times:")
    for agent, time in result["execution_time"].items():
        print(f"  - {agent}: {time:.2f} seconds")
    
    total_time = sum(result["execution_time"].values())
    print(f"  - Total: {total_time:.2f} seconds")
    
    # Save to file
    output_file = "example_blog_post.md"
    with open(output_file, "w") as f:
        f.write(f"# {blog_title}\n\n")
        f.write(f"{blog_post}\n\n")
        f.write(f"---\n\n")
        f.write(f"*Generated by Multi-Agent Blog Generator*\n")
        f.write(f"*Word Count: {metadata['word_count']} | ")
        f.write(f"Reading Time: {metadata['estimated_reading_time']} min*\n")
    
    print(f"\n✓ Blog post saved to: {output_file}")


if __name__ == "__main__":
    main()
